### ISSUE TITLE
Unable to try the out the application - error on npm start

### ISSUE THREAD

**Issue by Oscar-21** [vasansr/pro-mern-stack#7]
Hey, I love your book, especially the well thought out exercises; they are all too rare in programming books. 

I just started reading, so forgive me if I am jumping the gun, but I want to see what the final product will be like. The problem is I can not run the server. 

1. Ubuntu 16.04
2. node: v4.5
3. npm -v 2.15.9

1. npm install  in /pro-mern-stack (master)
2. npm start in /pro-mern-stack (master)

I get error
can't find dist/server.bundle.js

Thanks for the great book and any help you can give me so I can preview the end product of the book!

**Comment by vasansr** [comment]
Thanks!

You will need to compile the front-end, the server and then start.

```
$ npm compile
$ npm compile-server
$ npm start
```

**Comment by vasansr** [comment]
I've added instructions in the README as well.
